#!/bin/sh
set -e
latest_tag=$(git describe --abbrev=0 --tags)
goxz -d dist/$latest_tag -z -os windows,darwin,linux -arch amd64,386
ghr -u kobarasukimaro -r mackerel-plugin-aws-cognito-idp $latest_tag dist/$latest_tag
